name: Run tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "kustomize-build/**/*.ya?ml"

env:
  PR_REF: ${{ github.event.pull_request.head.ref }}
  DEFAULT_REF: ${{ github.event.repository.default_branch }}

jobs:
  kustomize:
    name: "Diff kustomize manifests against default branch"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.PR_REF }}
          fetch-depth: 2 # otherwise, you will failed to push refs to dest repo

      - name: Kustomize build and diff
        id: kustomize-diff
        uses: ./kustomize-build
        with:
          install_kustomize: true
          kustomize_version: 5.0.3
          kustomize_overlay_paths: "kustomize-build/test/kustomize/dev,kustomize-build/test/kustomize/prod"
          target_ref: ${{ env.DEFAULT_REF }}
          source_ref: ${{ env.PR_REF }}

      - name: Print rendered manifest
        run: |
          cat kustomize-build/test/kustomize/dev/rendered/rendered.yaml
          cat kustomize-build/test/kustomize/prod/rendered/rendered.yaml
